version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:management # rabbitmq 이미지 중 management 기능이 있는 rabbitmq-server까지 포함된 이미지를 실행
    container_name: rabbitmq_test
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5672:5672" # rabbitmq 기본통신포트
      - "15672:15672" # rabbitmq-server의 통신포트
    restart: always
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
    #   RABBITMQ_DEFAULT_USER: "admin"
    #   RABBITMQ_DEFAULT_PASS: "admin"